---
name: "github/ci/presubmit"

on:
  push:
    branches:
      - "!master"
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  presubmit:
    name: mumble-server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build
        run: ./tools/ci/build.sh

      - name: Test
        run: ./tools/ci/test.sh
